const DATA = [
  {
    cin:'DC9999900',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com',
    speciality:'hardware'
  },
];
export default DATA;