const DATA = [
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'AE88888',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
  {
    cin:'DC000000',
    firstName:'adib',
    lastName:'chiguer',
    email:'chigueradib9@gmail.com'
  },
];
export default DATA;